# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_eve_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='eve_pics',
            name='eve_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
