# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magzine', '0003_auto_20171012_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Cont',
        ),
    ]
