# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20171011_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='gmail_link',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='linkdin_link',
        ),
        migrations.AddField(
            model_name='bio',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='g_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='ln_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
